/*
 * JOB_PORTAL
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"os"
)

type UpdateProfileBody struct {

	Name string `json:"name,omitempty"`

	FirstNiche string `json:"firstNiche,omitempty"`

	SecondNiche string `json:"secondNiche,omitempty"`

	ThirdNiche string `json:"thirdNiche,omitempty"`

	Email string `json:"email,omitempty"`

	Resume **os.File `json:"resume,omitempty"`
}
