/*
 * JOB_PORTAL
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Post66d5501fe452d7bffe026053Body struct {

	Name string `json:"name,omitempty"`

	Email string `json:"email,omitempty"`

	Phone int32 `json:"phone,omitempty"`

	Address string `json:"address,omitempty"`

	CoverLetter string `json:"coverLetter,omitempty"`
}
