/*
 * JOB_PORTAL
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"os"
)

type UserRegisterBody struct {

	Name string `json:"name,omitempty"`

	Email string `json:"email,omitempty"`

	Phone int32 `json:"phone,omitempty"`

	Address string `json:"address,omitempty"`

	Password int32 `json:"password,omitempty"`

	Role string `json:"role,omitempty"`

	FirstNiche string `json:"firstNiche,omitempty"`

	SecondNiche string `json:"secondNiche,omitempty"`

	ThirdNiche string `json:"thirdNiche,omitempty"`

	Resume **os.File `json:"resume,omitempty"`

	CoverLetter string `json:"coverLetter,omitempty"`
}
